# Generated by Django 5.0.4 on 2024-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=300)),
                ('category', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Clothes'), (3, 'Shoes')])),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
